/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import Clases.Cls_Report;
import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author adis0
 */
public class Frm_Reporte extends javax.swing.JInternalFrame {

    Cls_Report reporte;

    /**
     * Creates new form Frm_Reportes
     */
    public Frm_Reporte() {
        initComponents();
    }

    private void limpiar() {
        jbtngMedicina.clearSelection();
        txtNombreArchivo.setText("");
        jdc_de.setDate(null);
        jdc_hasta.setDate(null);
        lblRuta.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtngMedicina = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jrbtnComprada = new javax.swing.JRadioButton();
        jrbtnDonada = new javax.swing.JRadioButton();
        jrbtnMuestra = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jdc_de = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jdc_hasta = new com.toedter.calendar.JDateChooser();
        txtNombreArchivo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGenerarArchivo = new javax.swing.JButton();
        btnRuta = new javax.swing.JButton();
        lblRuta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Reportes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Reportes");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setText("Generar reportes de entradas y salidas por fechas de Medicina Comprada, Donada y Muestra.");

        jbtngMedicina.add(jrbtnComprada);
        jrbtnComprada.setText("Medicina Comprada");

        jbtngMedicina.add(jrbtnDonada);
        jrbtnDonada.setText("Medicina Donada");

        jbtngMedicina.add(jrbtnMuestra);
        jrbtnMuestra.setText("Muestra Medica");

        jLabel1.setText("Desde:");

        jdc_de.setDateFormatString("yyyy/MM/dd");

        jLabel4.setText("Hasta");

        jdc_hasta.setDateFormatString("yyyy/MM/dd");

        jLabel5.setText("Nombrar Archivo:");

        btnGenerarArchivo.setText("Generar");
        btnGenerarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarArchivoActionPerformed(evt);
            }
        });

        btnRuta.setText("Seleccionar Ruta");
        btnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaActionPerformed(evt);
            }
        });

        jLabel6.setText("Ruta: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jrbtnComprada)
                                            .addGap(85, 85, 85)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jdc_de, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRuta))
                                        .addGap(69, 69, 69)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdc_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jrbtnDonada))
                                        .addGap(87, 87, 87)
                                        .addComponent(jrbtnMuestra))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblRuta))))))
                    .addComponent(btnGenerarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbtnMuestra, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrbtnComprada)
                        .addComponent(jrbtnDonada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdc_de, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdc_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRuta)
                    .addComponent(lblRuta)
                    .addComponent(jLabel6))
                .addGap(61, 61, 61)
                .addComponent(btnGenerarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarArchivoActionPerformed
        // TODO add your handling code here:
        int tipoMed = 0;
        if (jrbtnComprada.isSelected()) {
            tipoMed = 1;
        }
        if (jrbtnDonada.isSelected()) {
            tipoMed = 2;
        }
        if (jrbtnMuestra.isSelected()) {
            tipoMed = 3;
        }

        boolean rep = false;

        if (jdc_de.getCalendar() != null) {
            if (jdc_hasta.getCalendar() != null) {
                Date fecha1 = jdc_de.getDate();
                long d1 = fecha1.getTime();
                System.out.println(fecha1);
                System.out.println(d1);
                java.sql.Date fechaSql1 = new java.sql.Date(d1);
                System.out.println(fechaSql1);

                Date fecha2 = jdc_hasta.getDate();
                long d2 = fecha2.getTime();
                java.sql.Date fechaSql2 = new java.sql.Date(d2);

                if (txtNombreArchivo.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Por favor asigne un nombre al archivo");
                } else if (lblRuta.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Seleccione la ruta donde almacenará el archivo");
                } else {
                    String ruta = lblRuta.getText();
                    System.out.println("Adios");
                    String nombreArchivo = txtNombreArchivo.getText();
                    reporte = new Cls_Report();
                    rep = reporte.crearReporte(nombreArchivo, fechaSql1, fechaSql2, tipoMed, ruta);
                    if (rep) {
                        JOptionPane.showMessageDialog(null, "Reporte Creado");
                        limpiar();
                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo crear el reporte");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Campos fecha vacios porfavor llenar registros.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Campos fecha vacios porfavor llenar registros.");
        }        
    }//GEN-LAST:event_btnGenerarArchivoActionPerformed

    private void btnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaActionPerformed
        // TODO add your handling code here:
        lblRuta.setText("");
        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int resultado = selectorArchivos.showOpenDialog(this);
        File archivo = selectorArchivos.getSelectedFile();
        if ((archivo == null) || (archivo.getName().equals(""))) {
            JOptionPane.showMessageDialog(this, "Nombre de archivo inválido", "Nombre de archivo inválido", JOptionPane.ERROR_MESSAGE);
        } else {
            lblRuta.setText(archivo.getAbsolutePath());
        }

    }//GEN-LAST:event_btnRutaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarArchivo;
    private javax.swing.JButton btnRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jbtngMedicina;
    private com.toedter.calendar.JDateChooser jdc_de;
    private com.toedter.calendar.JDateChooser jdc_hasta;
    private javax.swing.JRadioButton jrbtnComprada;
    private javax.swing.JRadioButton jrbtnDonada;
    private javax.swing.JRadioButton jrbtnMuestra;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JTextField txtNombreArchivo;
    // End of variables declaration//GEN-END:variables
}
